apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/maildomain: "true"
    io.kompose.service: equmedia-mail-db
  name: equmedia-mail-db
spec:
  containers:
    - env:
        - name: POSTGRES_DB
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_USER
      image: postgres:13-alpine
      name: equmedia-mail-db
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: maildata
  restartPolicy: OnFailure
  volumes:
    - name: maildata
      persistentVolumeClaim:
        claimName: maildata
status: {}
